## Tabela Price

**Tabela Price** ou **sistema francês de amortização** é um método usado em amortização de empréstimos em que o valor das prestações (parcelas) é constante.

No sistema da tabela Price o combinado é que se deve pagar uma dívida $\$_0$ em $n$ prestação idênticas de valor $x$ com uma taxa de juros $R_{anual}$ anual. O termo $1 + R_{anual}$ é bastante frequente, por isso lançamos mão da váriavel auxiliar $Z_{anual} = 1 + R_{anual}$. Caso as prestações sejam pagas mensalmente, precisamos de $Z_{mensal}$, dado por $Z_{mensal} = Z_{anual}^{\frac{1}{12}} = (1+R_{anual})^{\frac{1}{12}}$.

Geralmente, o que se sabe é o valor que se quer financiar, $\$_0$; a quantidade $n$ de parcelas e a taxa de juros mensal, $R_{mensal} = R_m \rightarrow Z_m = 1 + R_m$. 

Com essas informações, podemos calcular as seguintes quantidades para cada parcela:

* Prestação:   $x = \frac{(Z_m - 1)Z_m^n}{Z_m^n-1}\$_0$


* Juros: $\$_{juros} = \frac{(Z_m-1)(Z_m^n-Z_m^{k-1})}{(Z_m^n-1)}\$_0$, juros pago na $k-ésima$ parcela


* Amortização: $\$_{amortização} = \frac{(Z_m-1)Z_m^{k-1}}{(Z_m^n-1)}\$_0$


* Dívida: $D_k = \frac{(Z_m^n-Z_m^k)}{(Z_m^n-1)}\$_0$

In [4]:
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:.2f}'.format
import matplotlib.pyplot as plt

pv = 30000       # Valor emprestado ou financiado
Z = 1 + 0.01     # 1 + taxa de juros mensal (1%)
n = 12           # Quantidade de parcelas

In [2]:
# Array com a quantidade de parcelas
N = np.arange(n+1)

# Array com o valor das parcelas, que deve ser constante
x = ((Z-1)*Z**n/(Z**n-1))*pv
X = np.zeros(n+1)
X = X + x
X[0] = 0

# Arrays com o valor da dívida, juros e amortização
divida = np.zeros(n+1)
juros = np.zeros(n+1)
for i in range(n):
    k=i+1
    divida[k] = (Z**n-Z**k)/(Z**n-1)*pv
    juros[k] = (Z-1)*(Z**n-Z**(k-1))/(Z**n-1)*pv
amortizacao = X - juros

In [5]:
# Tabela com os resultados obtidos
df = pd.DataFrame()
df['Nº'] = N
df['Prestação'] = X
df['Juros'] = juros
df['Amortização'] = amortizacao
df['Dívida'] = divida
df

    Nº  Prestação  Juros  Amortização   Dívida
0    0       0.00   0.00         0.00     0.00
1    1    2665.46 300.00      2365.46 27634.54
2    2    2665.46 276.35      2389.12 25245.42
3    3    2665.46 252.45      2413.01 22832.41
4    4    2665.46 228.32      2437.14 20395.27
5    5    2665.46 203.95      2461.51 17933.76
6    6    2665.46 179.34      2486.13 15447.63
7    7    2665.46 154.48      2510.99 12936.64
8    8    2665.46 129.37      2536.10 10400.55
9    9    2665.46 104.01      2561.46  7839.09
10  10    2665.46  78.39      2587.07  5252.02
11  11    2665.46  52.52      2612.94  2639.07
12  12    2665.46  26.39      2639.07     0.00